import { notFound } from 'next/navigation';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import type { Report } from '@/lib/types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { FileText, Lightbulb, Puzzle, Target } from 'lucide-react';
import DownloadButtons from './download-buttons';

async function getReport(id: string): Promise<Report | null> {
  const docRef = doc(db, 'reports', id);
  const docSnap = await getDoc(docRef);

  if (!docSnap.exists()) {
    return null;
  }

  return { id: docSnap.id, ...docSnap.data() } as Report;
}

export default async function ReportPage({ params }: { params: { id:string } }) {
  const report = await getReport(params.id);

  if (!report) {
    notFound();
  }

  return (
    <div className="p-4 sm:p-6 lg:p-8">
      <header className="mb-8 flex flex-col items-start gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <Badge variant="outline">{report.createdAt.toDate().toLocaleDateString()}</Badge>
          <h1 className="font-headline mt-2 text-3xl font-bold tracking-tight text-foreground">
            {report.title}
          </h1>
          <p className="mt-2 text-muted-foreground">
            AI-generated signal report for <span className="font-semibold text-foreground">{report.inputs.businessVertical}</span>.
          </p>
        </div>
        <div className="no-print">
          <DownloadButtons reportContent={report.content} reportTitle={report.title} />
        </div>
      </header>

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-3 print-container">
        <div className="lg:col-span-2">
            <Card>
                <CardHeader>
                    <CardTitle>Generated Report</CardTitle>
                    <CardDescription>This report was generated by AI agents based on your inputs.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="prose prose-sm max-w-none dark:prose-invert">
                        <pre className="whitespace-pre-wrap font-body text-base leading-relaxed">{report.content}</pre>
                    </div>
                </CardContent>
            </Card>
        </div>
        <div className="lg:col-span-1 no-print">
            <Card className="sticky top-4">
                <CardHeader>
                    <CardTitle>Input Parameters</CardTitle>
                    <CardDescription>The inputs used for this analysis.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 text-sm">
                    <div>
                        <h4 className="flex items-center gap-2 font-semibold mb-2"><Lightbulb className="h-4 w-4 text-muted-foreground" /> JTBD Hunches</h4>
                        <p className="text-muted-foreground pl-6 border-l-2 ml-2">{report.inputs.jtbdHunches}</p>
                    </div>
                     <Separator />
                    <div>
                        <h4 className="flex items-center gap-2 font-semibold mb-2"><Puzzle className="h-4 w-4 text-muted-foreground" /> User Struggles</h4>
                        <p className="text-muted-foreground pl-6 border-l-2 ml-2">{report.inputs.struggles}</p>
                    </div>
                    <Separator />
                    <div>
                        <h4 className="flex items-center gap-2 font-semibold mb-2"><Target className="h-4 w-4 text-muted-foreground" /> Business Vertical</h4>
                        <p className="text-muted-foreground pl-6 border-l-2 ml-2">{report.inputs.businessVertical}</p>
                    </div>
                     <Separator />
                    <div>
                        <h4 className="flex items-center gap-2 font-semibold mb-2"><FileText className="h-4 w-4 text-muted-foreground" /> USPs</h4>
                        <p className="text-muted-foreground pl-6 border-l-2 ml-2">{report.inputs.usps}</p>
                    </div>
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
